manifest = "66a189891311f99e5cd224877374ba0e0a55f46624581435cfda1be3bfff1de5"

[[dependency]]
package = "github.com/buckaroo-pm/boost-config"
target = "//:config"

[[dependency]]
package = "github.com/buckaroo-pm/boost-integer"
target = "//:integer"

[[dependency]]
package = "github.com/buckaroo-pm/boost-iterator"
target = "//:iterator"

[[dependency]]
package = "github.com/buckaroo-pm/boost-static_assert"
target = "//:static_assert"

[lock."github.com/buckaroo-pm/boost-config"]
versions = [ "1.49.0" ]
revision = "d3a4298d018723c63cbecab085f0aa8a6e2e6211"

[lock."github.com/buckaroo-pm/boost-detail"]
versions = [ "1.49.0" ]
revision = "72b1919a324229aafc0c3c805ec8e22b985fcbeb"

[lock."github.com/buckaroo-pm/boost-integer"]
versions = [ "1.49.0" ]
revision = "943a3af66debb25f73e9146a99fc5b13121327cd"

[lock."github.com/buckaroo-pm/boost-iterator"]
versions = [ "1.49.0" ]
revision = "5cd48dfa9f727ec204e02841e47e1993140ac37a"

[lock."github.com/buckaroo-pm/boost-mpl"]
versions = [ "1.49.0" ]
revision = "815ba56319a8245f79f14bf21a5501aa4a3ee416"

[lock."github.com/buckaroo-pm/boost-preprocessor"]
versions = [ "1.49.0" ]
revision = "63176e5e4eef9e85cbb2d42119475a0f5e80e03b"

[lock."github.com/buckaroo-pm/boost-static_assert"]
versions = [ "1.49.0" ]
revision = "616b2c58fc555322b60b1c621090c7feb2a8d8b1"

[lock."github.com/buckaroo-pm/boost-type_traits"]
versions = [ "1.49.0" ]
revision = "5303008d2190d8ba849831783ae3357c9d91425f"

[lock."github.com/buckaroo-pm/boost-utility"]
versions = [ "1.49.0" ]
revision = "2737802982bb4a4b52346c24a2aeba88ee35ee4e"
