manifest = "c679929d70e75cf7b4078e287faa08f1ade0368f7e7803111b53318e62be62ae"

[[dependency]]
package = "github.com/buckaroo-pm/boost-config"
target = "//:config"

[[dependency]]
package = "github.com/buckaroo-pm/boost-integer"
target = "//:integer"

[[dependency]]
package = "github.com/buckaroo-pm/boost-iterator"
target = "//:iterator"

[[dependency]]
package = "github.com/buckaroo-pm/boost-static_assert"
target = "//:static_assert"

[lock."github.com/buckaroo-pm/boost-config"]
versions = [ "1.46.1" ]
revision = "72805600b44f7e4b63be95f755d9bd3f6507a031"

[lock."github.com/buckaroo-pm/boost-detail"]
versions = [ "1.46.1" ]
revision = "a216a8a0d4ca8e9a0106992dac0d491de7831dcd"

[lock."github.com/buckaroo-pm/boost-integer"]
versions = [ "1.46.1" ]
revision = "118f07e0b14205cffb36b80d695c595e9869b0c1"

[lock."github.com/buckaroo-pm/boost-iterator"]
versions = [ "1.46.1" ]
revision = "b46c22e77dc49a7f77e02a406d6beb8be414eb41"

[lock."github.com/buckaroo-pm/boost-mpl"]
versions = [ "1.46.1" ]
revision = "2c2390d3c017d72027a7f74adfc503fc9ca61861"

[lock."github.com/buckaroo-pm/boost-preprocessor"]
versions = [ "1.46.1" ]
revision = "76d2b93451ed144b54015f921ee5273473bb8796"

[lock."github.com/buckaroo-pm/boost-static_assert"]
versions = [ "1.46.1" ]
revision = "dda6fcaf4a79f8eebd3ad253c73f5b684e413d7d"

[lock."github.com/buckaroo-pm/boost-type_traits"]
versions = [ "1.46.1" ]
revision = "53791bee68fb0891b2e0b0755373281e40e981e7"

[lock."github.com/buckaroo-pm/boost-utility"]
versions = [ "1.46.1" ]
revision = "c80181b4bd2177956c6794f43ae48de76f6b0f59"
