manifest = "164992190a456feee85a3d220d6c8c75de9ea8982c690418d0b08068bcd18059"

[[dependency]]
package = "github.com/buckaroo-pm/boost-config"
target = "//:config"

[[dependency]]
package = "github.com/buckaroo-pm/boost-integer"
target = "//:integer"

[[dependency]]
package = "github.com/buckaroo-pm/boost-iterator"
target = "//:iterator"

[[dependency]]
package = "github.com/buckaroo-pm/boost-static_assert"
target = "//:static_assert"

[lock."github.com/buckaroo-pm/boost-config"]
versions = [ "1.42.0" ]
revision = "bdbfd4f7cb2eb6f0a1d87672c0564f4909c4cb20"

[lock."github.com/buckaroo-pm/boost-detail"]
versions = [ "1.42.0" ]
revision = "782ecf1ed3fb2e1eecf9b7cc91c596886d6f2acf"

[lock."github.com/buckaroo-pm/boost-integer"]
versions = [ "1.42.0" ]
revision = "32665b4a77378e96b1fd6ffb722d75c514f8122e"

[lock."github.com/buckaroo-pm/boost-iterator"]
versions = [ "1.42.0" ]
revision = "094e96a9c4abbc8465bf19aff847aeb4571f1223"

[lock."github.com/buckaroo-pm/boost-mpl"]
versions = [ "1.42.0" ]
revision = "93cfcb2ed35349c026dfadd868d4c8c2f76efc67"

[lock."github.com/buckaroo-pm/boost-preprocessor"]
versions = [ "1.42.0" ]
revision = "ad64e4e9f85cad0ed501c3eaf0faba2a9bfc3dc3"

[lock."github.com/buckaroo-pm/boost-static_assert"]
versions = [ "1.42.0" ]
revision = "12ae8c5bf22e2da1edfcf02390b69d59c25c1001"

[lock."github.com/buckaroo-pm/boost-type_traits"]
versions = [ "1.42.0" ]
revision = "d3cb1586ec0bb62cbe3cbfb8eadf4f759379fce6"

[lock."github.com/buckaroo-pm/boost-utility"]
versions = [ "1.42.0" ]
revision = "5ede30fc16f5822487be1b02337ba414ef4aae3c"
