manifest = "efcd9893d23ee8665972b9f7ca9603b43ee3a8149cbf32e879e1ae4535f44198"

[[dependency]]
package = "github.com/buckaroo-pm/boost-config"
target = "//:config"

[[dependency]]
package = "github.com/buckaroo-pm/boost-integer"
target = "//:integer"

[[dependency]]
package = "github.com/buckaroo-pm/boost-iterator"
target = "//:iterator"

[[dependency]]
package = "github.com/buckaroo-pm/boost-static_assert"
target = "//:static_assert"

[lock."github.com/buckaroo-pm/boost-config"]
versions = [ "1.40.0" ]
revision = "3a9079edc4b058e42495a36ca7cbdc20675a64e3"

[lock."github.com/buckaroo-pm/boost-detail"]
versions = [ "1.40.0" ]
revision = "e71d7a0f72b577ee4f5dd702dfed18709ed72681"

[lock."github.com/buckaroo-pm/boost-integer"]
versions = [ "1.40.0" ]
revision = "8bda4592d2b32baf52ed50ed5809501a11beee71"

[lock."github.com/buckaroo-pm/boost-iterator"]
versions = [ "1.40.0" ]
revision = "f74b6424bae4e16ae8d4fed110629f0b1b0b97c6"

[lock."github.com/buckaroo-pm/boost-mpl"]
versions = [ "1.40.0" ]
revision = "34ea913a6a676eca4dc1ea067668d38ac0da934f"

[lock."github.com/buckaroo-pm/boost-preprocessor"]
versions = [ "1.40.0" ]
revision = "85f257f138e6eae7e61906452db3ed2158f6def9"

[lock."github.com/buckaroo-pm/boost-static_assert"]
versions = [ "1.40.0" ]
revision = "bd7e994a6782500e1b4fb1ccf7b92a3aafef3bc4"

[lock."github.com/buckaroo-pm/boost-type_traits"]
versions = [ "1.40.0" ]
revision = "2da091c54485dc8752239107764d88a5f7b1bf71"

[lock."github.com/buckaroo-pm/boost-utility"]
versions = [ "1.40.0" ]
revision = "b459dd5be9de4e4969097056bbac57a36112fa76"
