targets = ["//:system"]

[[dependency]]
package = "github.com/buckaroo-pm/boost-config"
version = "1.44.0"

[[dependency]]
package = "github.com/buckaroo-pm/boost-static_assert"
version = "1.44.0"

[[dependency]]
package = "github.com/buckaroo-pm/boost-iterator"
version = "1.44.0"

[[dependency]]
package = "github.com/buckaroo-pm/boost-integer"
version = "1.44.0"