manifest = "b90f35d30454c651d4e616b76317cd0f703e7b930b216f7def87109a18ede998"

[[dependency]]
package = "github.com/buckaroo-pm/boost-config"
target = "//:config"

[[dependency]]
package = "github.com/buckaroo-pm/boost-integer"
target = "//:integer"

[[dependency]]
package = "github.com/buckaroo-pm/boost-iterator"
target = "//:iterator"

[[dependency]]
package = "github.com/buckaroo-pm/boost-predef"
target = "//:predef"

[[dependency]]
package = "github.com/buckaroo-pm/boost-static_assert"
target = "//:static_assert"

[lock."github.com/buckaroo-pm/boost-assert"]
versions = [ "1.56.0" ]
revision = "9d1a6e0a4a74ad3af0ade7285ab5edd52c6fd860"

[lock."github.com/buckaroo-pm/boost-config"]
versions = [ "1.56.0" ]
revision = "edb8562f816250216903f89ec4d9ac0961a922a1"

[lock."github.com/buckaroo-pm/boost-core"]
versions = [ "1.56.0" ]
revision = "599096bd0a9ca5ecd901886f09046e3f7ce05556"

[lock."github.com/buckaroo-pm/boost-detail"]
versions = [ "1.56.0" ]
revision = "baeb2fb09197e1422a40481e9080e17c75cd50cf"

[lock."github.com/buckaroo-pm/boost-integer"]
versions = [ "1.56.0" ]
revision = "68e4e54f50d15baa85f355a3ad9c3004126883f6"

[lock."github.com/buckaroo-pm/boost-iterator"]
versions = [ "1.56.0" ]
revision = "9f169f3466207e7d685e0cf4f369447f527d92e8"

[lock."github.com/buckaroo-pm/boost-mpl"]
versions = [ "1.56.0" ]
revision = "6f5e6228b91a06843e74ab0d5ea58c043fdf24e4"

[lock."github.com/buckaroo-pm/boost-predef"]
versions = [ "1.56.0" ]
revision = "86f4d74778d6d587a57a6905604abfb2ee00f939"

[lock."github.com/buckaroo-pm/boost-preprocessor"]
versions = [ "1.56.0" ]
revision = "ad21a117be237ab693f723782c5581bb58ce8875"

[lock."github.com/buckaroo-pm/boost-static_assert"]
versions = [ "1.56.0" ]
revision = "37f8e9a9f7a9e93ab1ebed5fc2f8614d3c52e710"

[lock."github.com/buckaroo-pm/boost-type_traits"]
versions = [ "1.56.0" ]
revision = "9641085a42a25ca196d08d542862616f877cf693"

[lock."github.com/buckaroo-pm/boost-utility"]
versions = [ "1.56.0" ]
revision = "4cb87af8e2e77f0826f17eca369395ba86ef1a17"
