targets = [ "//:system" ]

[[dependency]]
package = "github.com/buckaroo-pm/boost-predef"
version = "1.71.0"

[[dependency]]
package = "github.com/buckaroo-pm/boost-config"
version = "1.71.0"

[[dependency]]
package = "github.com/buckaroo-pm/boost-static_assert"
version = "1.71.0"

[[dependency]]
package = "github.com/buckaroo-pm/boost-iterator"
version = "1.71.0"

[[dependency]]
package = "github.com/buckaroo-pm/boost-integer"
version = "1.71.0"

[[dependency]]
package = "github.com/buckaroo-pm/boost-assert"
version = "1.71.0"

[[dependency]]
package = "github.com/buckaroo-pm/boost-core"
version = "1.71.0"
