manifest = "caa62697fae6864e23a6999f4b0c4802d2d1ac966c899e91dd589f63e7488821"

[[dependency]]
package = "github.com/buckaroo-pm/boost-config"
target = "//:config"

[[dependency]]
package = "github.com/buckaroo-pm/boost-integer"
target = "//:integer"

[[dependency]]
package = "github.com/buckaroo-pm/boost-iterator"
target = "//:iterator"

[[dependency]]
package = "github.com/buckaroo-pm/boost-static_assert"
target = "//:static_assert"

[lock."github.com/buckaroo-pm/boost-config"]
versions = [ "1.38.0" ]
revision = "f129de05f396dc4d6e5460a69f648766659d4e09"

[lock."github.com/buckaroo-pm/boost-detail"]
versions = [ "1.38.0" ]
revision = "be230f24a809ac41e584cfd6d843485073012a80"

[lock."github.com/buckaroo-pm/boost-integer"]
versions = [ "1.38.0" ]
revision = "e98d5641e227aabfdbadb9d50f4dfa7ebdab9e41"

[lock."github.com/buckaroo-pm/boost-iterator"]
versions = [ "1.38.0" ]
revision = "6dd67612ba4c341a9e3ff99e5716357bd6ac783d"

[lock."github.com/buckaroo-pm/boost-mpl"]
versions = [ "1.38.0" ]
revision = "67680c89217df7d12a280c75e861056e7482aa64"

[lock."github.com/buckaroo-pm/boost-preprocessor"]
versions = [ "1.38.0" ]
revision = "ac36cd1957ed21e9a63225331843132518c57537"

[lock."github.com/buckaroo-pm/boost-static_assert"]
versions = [ "1.38.0" ]
revision = "ace4995bb42d6021e9ac34cf80b159afa2aa7345"

[lock."github.com/buckaroo-pm/boost-type_traits"]
versions = [ "1.38.0" ]
revision = "052bc304465323f02bea64dca87d3db7c07b457b"

[lock."github.com/buckaroo-pm/boost-utility"]
versions = [ "1.38.0" ]
revision = "bced377b216e7336710ddbc86d94b09f4f9b0104"
